import "./globals.css";
import { Inter } from "next/font/google";
import Layout from "./components/Layout";
import Tabs from "./components/Tabs/Tabs";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
          <main>{children}</main>
        </Layout>
      </body>
    </html>
  );
}
